<?php

namespace Xible\Bundle\BkuBundle;

use Doctrine\ORM\EntityRepository;

/**
 * EntityRefSatkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRefSatkerRepository extends EntityRepository
{
}
