Xible\Bundle\BkuBundle\Entity\RefRekening:
    type: entity
    repositoryClass: Xible\Bundle\BkuBundle\Entity\RefRekeningRepository
    table: ref_rekening
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        kode:
            type: string
            nullable: true
            length: 9
            fixed: true
            default: '-'
            column: Kode
        nama:
            type: string
            nullable: true
            length: 250
            fixed: true
            default: '-'
            column: Nama
        saldoawal:
            type: decimal
            nullable: true
            precision: 18
            scale: 2
            default: '0.00'
    lifecycleCallbacks: {  }
