<?php

namespace Xible\Bundle\BkuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckRepository extends EntityRepository
{
}
