<?php

namespace Xible\Bundle\BkuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatJurnal01Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatJurnal01Repository extends EntityRepository
{
}
