<?php

namespace Xible\Bundle\BkuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RefRekananRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefRekananRepository extends EntityRepository
{
}
